### ISSUE TITLE
String.camelize with opal 0.11 not working

### ISSUE THREAD

**Issue by janbiedermann** [opal/opal-activesupport#16]
Try here:
http://opalrb.com/try/?code:class%20String%0A%20%20def%20underscore%0A%20%20%20%20%60%23%7Bself%7D.replace(%2F%5B-%5Cs%5D%2B%2Fg%2C%20%27_%27)%0A%20%20%20%20.replace(%2F(%5BA-Z%5Cd%5D%2B)(%5BA-Z%5D%5Ba-z%5D)%2Fg%2C%20%27%241_%242%27)%0A%20%20%20%20.replace(%2F(%5Ba-z%5Cd%5D)(%5BA-Z%5D)%2Fg%2C%20%27%241_%242%27)%0A%20%20%20%20.replace(%2F-%2Fg%2C%20%27_%27)%0A%20%20%20%20.toLowerCase()%60%0A%20%20end%0A%0A%20%20def%20camelize(first_letter%20%3D%20%3Aupper)%0A%20%20%20%20%60%23%7Bunderscore%7D.replace(%2F(%5E%7C_)(%5B%5E_%5D%2B)%2Fg%2C%20function(match%2C%20pre%2C%20word%2C%20index)%20%7B%0A%20%20%20%20%20%20var%20capitalize%20%3D%20%23%7Bfirst_letter%7D%20%3D%3D%3D%20%23%7B%3Aupper%7D%20%7C%7C%20index%20%3E%200%3B%0A%20%20%20%20%20%20return%20capitalize%20%3F%20word.substr(0%2C1).toUpperCase()%2Bword.substr(1)%20%3A%20word%3B%0A%20%20%20%20%7D)%60%0A%20%20end%0Aend%0A%0Aputs%20%22test%3A%22%20%2B%20%22ba_lla%22.camelize

**Comment by sfcgeorge** [comment]
Adding `.to_s` to each of the Native backtick blocks seems to work.
