### ISSUE TITLE
Add ActiveSupport::Concern

### ISSUE THREAD

**Issue by sfcgeorge** [opal/opal-activesupport#18]
Background: Hyperloop moves Rails models to the frontend using Opal. ActiveSupport::Concern is commonly used in models, and it's actually just a single file with no dependencies so it can easily be copied into the frontend. It seems like it would be a great addition to Opal/ActiveSupport as it's simple, self contained, and can be copied verbatim.

https://github.com/rails/rails/blob/5-2-stable/activesupport/lib/active_support/concern.rb

But I believe there's a bug in Opal that needs fixing first https://github.com/opal/opal/issues/1761

**Comment by sfcgeorge** [comment]
Alternatively this could be added before the Opal issue is fixed by using my patched version. But that's not as desirable as then the patch has to be maintained and re-applied if Rails changes concern.rb
https://github.com/opal/opal/issues/1761#issuecomment-363794502

**Comment by iliabylich** [comment]
Could you send a PR with your patch please?
> But that's not as desirable as then the patch has to be maintained and re-applied if Rails changes concern.rb

I think this module is stable and gets changed quite rarely.

**Comment by sfcgeorge** [comment]
That is true. I looked back through the Rails versions and yeah it barely changes. Okay I will PR thanks!

**Comment by sfcgeorge** [comment]
Opened this pull with patched concern.rb and patched concern_test.rb https://github.com/opal/opal-activesupport/pull/19

**Comment by iliabylich** [comment]
Fixed in #19
