### ISSUE TITLE
Submodule ActiveSupport?

### ISSUE THREAD

**Issue by wied03** [opal/opal-activesupport#6]
Any reason why the actual activesupport github repo can't be submodule'ed and with selective requires/selective tests/monkey patching?

This would DRY up the code some and make it easier to stay current with the actual AS repo

**Comment by elia** [comment]
I tried using the as repo directly at first but some of the implementations are very complex seemed to heavyweight for the fronted (eg. Localization support)

Also I actually use just object/blank and few methods for string and enumerable so the pressure for adding stuff was quite light.

**Comment by wied03** [comment]
Yeah. I had the same experience yesterday. Ideally I guess there should be a 'light' and full version. Perhaps this repo can be the light version and as opal keeps improving, eventually the rails activesupport project will run out of the box?

**Comment by elia** [comment]
Looks like a fair plan, btw took the first step today and moved the whole test suite to minitest in order to be able to just copy/uncomment the original tests.

(closing this btw)
